config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :admins
  devise_for :users, controllers: { confirmations: 'confirmations' }

  root to: 'books#index'

  ###
  # API NAMESPACE
  ###
  namespace :api do
    resources :books, only: %i[index show] do
      get 'page/:page', action: :index, on: :collection
    end
    resources :tags, only: :index
    get 'book_search', to: 'books#search'
    post 'tag_search', to: 'tags#search'
    resources :registrations, only: :create
    post 'fetch_review', to: 'reviews#fetch_review'
    get 'search_review', to: 'reviews#search_review'
    resource :auth_tokens, only: :create do
      patch 'refresh_token', to: 'auth_tokens#update'
    end
  end

  resources :books
  resources :tags, only: %i[new create]
  get 'tags/:tag', to: 'books#index', as: :tag
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include Validations::Books

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :reviews, dependent: :restrict_with_error
  has_one_attached :link
  has_one_attached :image

  accepts_nested_attributes_for :tags

  scope :fetch_by_tag_name, ->(name) { joins(:tags).merge(Tag.fetch_by_name(name)) }

  class << self
    def tagged_with(name)
      Tag.find_by!(name: name).books
    end

    def tag_counts
      Tag.select('tags.*, count(taggings.tag_id) as count')
         .joins(:taggings).group('taggings.tag_id')
    end
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map { |name| Tag.where(name: name.strip).first_or_create! }
  end

  def calc_rating
    rates = Review.where(book: self).pluck(:rate)
    return nil if rates.empty?

    (rates.sum.to_f / rates.length).round(1)
  end

  private

  def link_attached
    return if link.attached?

    errors.add(:link, ' file should be attached')
  end

  # rubocop:disable Style/GuardClause
  def image_attached
    if image.attached?
      correct_image_mime_type
    else
      errors.add(:image, ' should be attached')
    end
  end

  def correct_image_mime_type
    unless image.content_type.in?(%w[image/png image/jpg image/jpeg])
      errors.add(:image, 'must be a JPG or a PNG or a JPEG file')
    end
  end
  # rubocop:enable Style/GuardClause
end

app/controllers/api/books_controller.rb
# frozen_string_literal: true

class BooksController < API::ApplicationController
  PER_PAGE = 10

  def index
    @books = Book.order('created_at DESC')
                 .page(params[:page])
                 .per(PER_PAGE)
    render json: Serializers::Book.render(
      @books,
      root: :books,
      meta: { count: Book.all.count }
    )
  end

  def show
    @book = Book.find(params[:id])

    render json: Serializers::Book.render(@book, root: :book)
  end

  def search
    item = params[:item]
    @q = Book.ransack(title_or_author_i_cont: item)
    @books = @q.result.order('created_at DESC')
    render json: Serializers::Book.render(
      @books,
      root: :books,
      meta: { count: @books.count }
    )
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < BaseController
  before_action :set_book, only: %i[show edit update destroy]
  helper_method :sort_column, :sort_direction

  def index
    @books = if params[:tag]
               Book.tagged_with(params[:tag])
             else
               Book.order("#{sort_column} #{sort_direction}")
             end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.validate!('/book')
    @book.save

    redirect_to books_url
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def show; end

  def edit; end

  def update
    @book.assign_attributes(book_params)
    @book.validate!('/book')
    @book.save

    redirect_to book_url(@book)
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    @book.destroy

    redirect_to books_url
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def sort_column
    return nil if params[:sort] == 'tags'

    Book.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def book_params
    params.require(:book).permit(
      :link,
      :title,
      :author,
      :description,
      :image,
      :tag,
      { tag_ids: [] }
    )
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, books_path(sort: column, direction: direction), { class: css_class }
  end
end

app/views/books/_form.html.slim
= simple_form_for @book, url: url do |f|
  = f.input :link, as: :file, required: true, input_html: { accept: '.fb2', data: { max_file_size: 5.megabytes } }
  = f.input :title, as: 'text', required: true, input_html: { rows: 5 }, maxlength: 255
  = f.input :author, required: true, maxlength: 255
  = f.input :description, as: 'text', required: true, input_html: { rows: 10 }, maxlength: 5_000
  - if @book.image.present? && @book.image.persisted?
    img.img-fluid.mb-3 src="#{url_for(@book.image)}" alt=''
  = f.input :image, as: :file, required: true, input_html: { accept: '.jpg, .jpeg, .png', data: { max_file_size: 1.megabytes } }
  .error-file-size
  = f.input :tag_ids, as: :select, label: 'Genre', collection: Tag.order(:name), label_method: :name, input_html: { multiple: true }

  .col.text-center.mt-4.btn-block
    = link_to 'Cancel', books_url, class: 'btn btn-secondary'
    = f.button :submit, 'Save book', class: 'btn btn-primary ml-2'

app/views/books/edit.html.slim
.container
  .row
    .col-sm-9.col-md-7.mx-auto
      .card.col.my-5
        .card-body
          h5.card-title.text-center = 'Edit Book'
          = render 'form', url: book_url(@book)

app/views/books/index.html.slim
.attractions-list
  .col.text-center
    h2.my-3.text-center  = 'Books'
  .col.text-center
    = link_to 'Add Book', new_book_path, class: 'btn btn-primary mb-2'
    = link_to 'Add Genre', new_tag_path, class: 'btn btn-success mb-2 ml-2'
  .container-fluid
    .attractions-table-wrapper.sticky-header-table-wrapper
      table.table.table-hover.table-sm.table-striped.books-table
        thead
          tr
            th.sticky-cell.pl-2.pr-4 = sortable 'id'
            th.sticky-cell.pl-0.pr-4.text-nowrap = sortable 'title'
            th.sticky-cell.pl-0.pr-4.text-nowrap = sortable 'author'
            th.sticky-cell.pl-0.pr-4.text-nowrap = sortable 'description'
            th.sticky-cell.pl-0.pr-4.text-nowrap = 'Genre'
            th.sticky-cell.px-0.text-nowrap.pr-2
        tbody
          - if @books&.empty?
            tr
              th = 'No Books uploaded yet'
          - @books&.each do |book|
            tr.book-row data-link="#{book_path(book)}"
              th.pl-2.pr-4 = book.id
              td.pl-0.pr-4
                div style="min-width: 250px;" = book.title
              td.pl-0.pr-4
                div style="min-width: 200px;" = book.author
              td.pl-0.pr-4
                div style="min-width: 200px;" = book.description
                td.pl-0.pr-4
                  div style="min-width: 200px;"
                    = raw book.tags.map(&:name).map { |tag| link_to tag, tag_path(tag), class: 'badge badge-secondary' }.join(' ')
              td.px-0.text-center.pr-2
                = link_to 'Edit', edit_book_path(book), class: 'btn btn-success btn-sm mt-1'
                = link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm ml-1 mt-1'
  .col.text-center
    = link_to 'Books list', books_path, class: 'btn btn-secondary mb-2'

app/views/books/new.html.slim
.container
  .row
    .col-sm-9.col-md-7.mx-auto
      .card.col.my-5
        .card-body
          h5.card-title.text-center = 'Add Book'
          = render 'form', url: books_url

app/views/books/show.html.slim
.book-show
  .col.text-center
    h2 Book details
  .container.show-book-container
    table.table.table-striped.table-hover.show-book
      thead
      tbody
        tr.d-flex
          td.col-2 = 'Link'
          td = url_for @book.link
        tr.d-flex
          td.col-2 = 'Title'
          td = @book.title
        tr.d-flex
          td.col-2 = 'Author'
          td = @book.author
        tr.d-flex
          td.col-2 = 'Description'
          td = @book.description
        tr.d-flex
          td.col-2 = 'Image'
          td
            img.img-fluid src="#{url_for(@book.image)}" alt=''
        tr.d-flex
          td.col-2 = 'Genre'
          td
            - if @book.tags.any?
              = raw @book.tags&.map(&:name).map { |tag| link_to tag, tag_path(tag), class: 'badge badge-secondary' }.join(' ')
            - else
              | No genres added

    = link_to 'Back', books_url, class: 'btn btn-secondary'
br